summary: ''
description: ''
lock: '!inline f/devops/cost_report.script.lock'
kind: script
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties:
    lookback_days:
      type: number
      description: ''
      default: 1
    format:
      type: string
      description: ''
      default: text
  required: []
