summary: ''
description: ''
lock: '!inline f/devops/sdp_aws_correlate.script.lock'
kind: script
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties:
    ticket_id:
      type: string
      description: ''
    dry_run:
      type: boolean
      description: ''
      default: false
  required:
    - ticket_id
